import { useState, useEffect } from 'react';
import { purchaseLogAPI } from '../api';
import { Search, Package, TrendingUp, ShoppingBag, Calendar, FileDown, Plus, Trash2, ClipboardList, Filter } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function ItemSummary() {
  const today = new Date().toISOString().split('T')[0];

  const [allItems, setAllItems]   = useState([]);
  const [fromDate, setFromDate]   = useState('');
  const [toDate, setToDate]       = useState('');
  const [searchName, setSearchName] = useState('');
  const [loading, setLoading]     = useState(true);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [saving, setSaving]       = useState(false);
  const [formData, setFormData]   = useState({
    item_name: '', quantity: '', unit: 'pcs',
    price_per_unit: '', purchased_date: today, notes: ''
  });

  // Load ALL records on page open
  useEffect(() => {
    fetchAll();
  }, []);

  const fetchAll = async () => {
    setLoading(true);
    try {
      const res = await purchaseLogAPI.getAll();
      setAllItems(Array.isArray(res.data) ? res.data : []);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  // Filtered items based on date range + item name (live filter)
  const safeAllItems = Array.isArray(allItems) ? allItems : [];
  const filteredItems = safeAllItems.filter(item => {
    const d = item.purchased_date;
    if (fromDate && d < fromDate) return false;
    if (toDate   && d > toDate)   return false;
    if (searchName && item.item_name && !item.item_name.toLowerCase().includes(searchName.toLowerCase())) return false;
    return true;
  });

  // Aggregates
  const totalItems = filteredItems.length;
  const totalQty   = filteredItems.reduce((s, i) => s + parseFloat(i.quantity || 0), 0);
  const totalCost  = filteredItems.reduce((s, i) => s + parseFloat(i.total_cost || 0), 0);

  const handleSave = async (e) => {
    e.preventDefault();
    setSaving(true);
    try {
      await purchaseLogAPI.add(formData);
    } catch (err) {
      console.error(err);
    } finally {
      setIsModalOpen(false);
      setFormData({ item_name: '', quantity: '', unit: 'pcs', price_per_unit: '', purchased_date: today, notes: '' });
      setSaving(false);
      await fetchAll();
    }
  };

  const handleDelete = async (id) => {
    try {
      await purchaseLogAPI.delete(id);
    } catch (err) {
      console.error(err);
    } finally {
      await fetchAll();
    }
  };

  const downloadPDF = () => {
    if (!filteredItems.length) return;
    const doc = new jsPDF();
    doc.setFillColor(253, 246, 237);
    doc.rect(0, 0, 210, 297, 'F');
    doc.setFontSize(22); doc.setFont('helvetica','bold'); doc.setTextColor(181,65,23);
    doc.text('ITEM PURCHASE SUMMARY', 14, 22);
    doc.setFontSize(10); doc.setFont('helvetica','normal'); doc.setTextColor(100,116,139);
    const periodText = fromDate || toDate
      ? `Period: ${fromDate ? new Date(fromDate).toLocaleDateString() : 'Beginning'} — ${toDate ? new Date(toDate).toLocaleDateString() : 'Today'}`
      : 'All Records';
    doc.text(periodText, 14, 30);
    doc.text('Zahi Wood Work', 14, 36);
    doc.setFontSize(10); doc.setFont('helvetica','bold'); doc.setTextColor(30,41,59);
    doc.text(`Total: ${totalItems} purchases | Qty: ${totalQty} | Spent: LKR ${totalCost.toLocaleString()}`, 14, 48);
    autoTable(doc, {
      startY: 56,
      head: [['#','Purchase Date','Item Name','Qty','Unit','Price/Unit (LKR)','Total (LKR)','Notes']],
      body: filteredItems.map((item,i) => [
        i+1,
        new Date(item.purchased_date).toLocaleDateString(),
        item.item_name, item.quantity, item.unit,
        parseFloat(item.price_per_unit).toLocaleString(),
        parseFloat(item.total_cost).toLocaleString(),
        item.notes || '-'
      ]),
      theme: 'plain',
      headStyles: { textColor:[181,65,23], fontStyle:'bold', fontSize:8.5 },
      styles: { fontSize:8.5, cellPadding:2.5, textColor:[30,41,59] },
      columnStyles: { 0:{halign:'center',cellWidth:8}, 5:{halign:'right'}, 6:{halign:'right'} },
      didParseCell: data => {
        if (data.section==='body') data.cell.styles.fillColor = data.row.index%2===0 ? [255,255,255] : [253,246,237];
      }
    });
    const fy = doc.lastAutoTable.finalY + 10;
    doc.setFillColor(181,65,23); doc.rect(14,fy,182,10,'F');
    doc.setTextColor(255,255,255); doc.setFont('helvetica','bold'); doc.setFontSize(11);
    doc.text('GRAND TOTAL', 16, fy+7);
    const tt = `LKR ${totalCost.toLocaleString()}`;
    doc.text(tt, 196 - doc.getStringUnitWidth(tt)*11/doc.internal.scaleFactor, fy+7);
    doc.setFontSize(9); doc.setFont('helvetica','normal'); doc.setTextColor(100,116,139);
    doc.text('Generated by Zahi Wood Work Management System', 14, 285);
    doc.save(`Purchase_Summary.pdf`);
  };

  return (
    <div className="space-y-6">

      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold text-slate-900 tracking-tight">Item Summary</h1>
          <p className="text-slate-500 mt-1">Track every item you purchase for your workshop.</p>
        </div>
        <div className="flex gap-3">
          {filteredItems.length > 0 && (
            <button onClick={downloadPDF} className="btn-secondary flex items-center gap-2">
              <FileDown className="w-4 h-4" /><span>PDF</span>
            </button>
          )}
          <button onClick={() => setIsModalOpen(true)} className="btn-primary flex items-center gap-2">
            <Plus className="w-4 h-4" /><span>Add Purchase</span>
          </button>
        </div>
      </div>

      <div className="card">
        <div className="flex flex-col gap-3">
          <div className="flex items-center gap-2 text-slate-600 font-semibold">
            <Filter className="w-4 h-4" /> Filter Records
          </div>
          <div className="flex flex-col sm:flex-row items-end gap-3">
            {/* Item Name Search */}
            <div className="flex-1">
              <label className="block text-xs font-medium text-slate-500 mb-1">Item Name</label>
              <div className="relative">
                <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
                <input type="text" placeholder="Search item name..." className="input-field pl-9"
                  value={searchName} onChange={e => setSearchName(e.target.value)} />
              </div>
            </div>
            {/* From Date */}
            <div className="flex-1">
              <label className="block text-xs font-medium text-slate-500 mb-1">From Date</label>
              <input type="date" className="input-field"
                value={fromDate} onChange={e => setFromDate(e.target.value)} />
            </div>
            {/* To Date */}
            <div className="flex-1">
              <label className="block text-xs font-medium text-slate-500 mb-1">To Date</label>
              <input type="date" className="input-field"
                value={toDate} onChange={e => setToDate(e.target.value)} />
            </div>
            {/* Clear */}
            <button onClick={() => { setFromDate(''); setToDate(''); setSearchName(''); }}
              className="btn-secondary text-sm px-4 whitespace-nowrap">
              Clear All
            </button>
          </div>
          {/* Active filters indicator */}
          {(fromDate || toDate || searchName) && (
            <div className="flex flex-wrap gap-2 pt-1">
              {searchName && (
                <span className="bg-blue-100 text-blue-700 text-xs font-medium px-2 py-1 rounded-full flex items-center gap-1">
                  Item: "{searchName}"
                  <button onClick={() => setSearchName('')} className="hover:text-blue-900">×</button>
                </span>
              )}
              {fromDate && (
                <span className="bg-green-100 text-green-700 text-xs font-medium px-2 py-1 rounded-full flex items-center gap-1">
                  From: {new Date(fromDate).toLocaleDateString()}
                  <button onClick={() => setFromDate('')} className="hover:text-green-900">×</button>
                </span>
              )}
              {toDate && (
                <span className="bg-green-100 text-green-700 text-xs font-medium px-2 py-1 rounded-full flex items-center gap-1">
                  To: {new Date(toDate).toLocaleDateString()}
                  <button onClick={() => setToDate('')} className="hover:text-green-900">×</button>
                </span>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <div className="bg-blue-50 border border-blue-200 rounded-xl p-5 flex items-center gap-4">
          <div className="p-3 bg-blue-100 rounded-lg"><Package className="w-6 h-6 text-blue-600" /></div>
          <div><p className="text-sm text-blue-600 font-medium">Total Purchases</p>
            <p className="text-2xl font-bold text-blue-800">{totalItems}</p></div>
        </div>
        <div className="bg-purple-50 border border-purple-200 rounded-xl p-5 flex items-center gap-4">
          <div className="p-3 bg-purple-100 rounded-lg"><ShoppingBag className="w-6 h-6 text-purple-600" /></div>
          <div><p className="text-sm text-purple-600 font-medium">Total Quantity</p>
            <p className="text-2xl font-bold text-purple-800">{totalQty}</p></div>
        </div>
        <div className="bg-orange-50 border border-orange-200 rounded-xl p-5 flex items-center gap-4">
          <div className="p-3 bg-orange-100 rounded-lg"><TrendingUp className="w-6 h-6 text-orange-600" /></div>
          <div><p className="text-sm text-orange-600 font-medium">Total Spent</p>
            <p className="text-2xl font-bold text-orange-800">LKR {totalCost.toLocaleString()}</p></div>
        </div>
      </div>

      {/* Table */}
      <div className="card overflow-hidden p-0">
        <div className="px-6 py-4 bg-slate-50 border-b border-slate-200 flex items-center justify-between">
          <h2 className="font-bold text-slate-800 flex items-center gap-2">
            <ClipboardList className="w-5 h-5 text-slate-500" />
            Purchase Records
            {(fromDate || toDate) && (
              <span className="bg-blue-100 text-blue-700 text-xs font-bold px-2 py-0.5 rounded-full">
                Filtered
              </span>
            )}
          </h2>
          <span className="text-sm text-slate-500">{filteredItems.length} records</span>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full min-w-[640px]">
            <thead>
              <tr>
                <th className="table-header">#</th>
                <th className="table-header">Purchase Date</th>
                <th className="table-header">Item Name</th>
                <th className="table-header">Quantity</th>
                <th className="table-header">Price/Unit (LKR)</th>
                <th className="table-header">Total (LKR)</th>
                <th className="table-header">Notes</th>
                <th className="table-header text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {loading ? (
                <tr><td colSpan="8" className="text-center py-10 text-slate-400">
                  <div className="animate-spin rounded-full h-8 w-8 border-4 border-blue-600 border-t-transparent mx-auto mb-2"></div>
                  Loading...
                </td></tr>
              ) : filteredItems.length === 0 ? (
                <tr><td colSpan="8" className="text-center py-12 text-slate-400">
                  <Package className="w-10 h-10 mx-auto mb-2 opacity-30" />
                  <p>No purchase records found.</p>
                  <button onClick={() => setIsModalOpen(true)} className="mt-3 text-blue-600 text-sm hover:underline">
                    + Add your first purchase record
                  </button>
                </td></tr>
              ) : (
                filteredItems.map((item, index) => (
                  <tr key={item.id} className="hover:bg-slate-50 transition-colors">
                    <td className="table-cell text-center text-slate-400 text-sm">{index + 1}</td>
                    <td className="table-cell">
                      <span className="inline-flex items-center gap-1 text-blue-700 font-medium text-sm bg-blue-50 px-2 py-0.5 rounded">
                        <Calendar className="w-3 h-3" />
                        {new Date(item.purchased_date).toLocaleDateString('en-GB', {day:'2-digit',month:'short',year:'numeric'})}
                      </span>
                    </td>
                    <td className="table-cell font-semibold text-slate-900">{item.item_name}</td>
                    <td className="table-cell">{item.quantity} {item.unit}</td>
                    <td className="table-cell">LKR {parseFloat(item.price_per_unit||0).toLocaleString()}</td>
                    <td className="table-cell font-semibold text-emerald-700">LKR {parseFloat(item.total_cost||0).toLocaleString()}</td>
                    <td className="table-cell text-slate-400 text-sm">{item.notes || '—'}</td>
                    <td className="table-cell text-right">
                      <button onClick={() => handleDelete(item.id)}
                        className="text-red-500 hover:text-red-700 p-1 hover:bg-red-50 rounded">
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
            {filteredItems.length > 0 && (
              <tfoot>
                <tr className="bg-slate-900">
                  <td colSpan="5" className="table-cell text-white font-bold">Grand Total</td>
                  <td className="table-cell text-emerald-400 font-bold">LKR {totalCost.toLocaleString()}</td>
                  <td colSpan="2"></td>
                </tr>
              </tfoot>
            )}
          </table>
        </div>
      </div>

      {/* Add Purchase Modal */}
      {isModalOpen && (
        <div className="fixed inset-0 bg-slate-900/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-xl shadow-xl w-full max-w-md overflow-hidden">
            <div className="px-6 py-4 border-b border-slate-100 flex justify-between items-center">
              <h3 className="text-lg font-semibold text-slate-900">Add Purchase Record</h3>
              <button onClick={() => setIsModalOpen(false)} className="text-slate-400 hover:text-slate-600 text-2xl leading-none">×</button>
            </div>
            <form onSubmit={handleSave} className="p-6 space-y-4">
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">Item Name</label>
                <input required type="text" className="input-field" placeholder="e.g. Plywood 18mm"
                  value={formData.item_name} onChange={e => setFormData({...formData, item_name: e.target.value})} />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-1">Quantity</label>
                  <input required type="number" min="1" className="input-field"
                    value={formData.quantity} onChange={e => setFormData({...formData, quantity: e.target.value})} />
                </div>
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-1">Unit</label>
                  <select className="input-field" value={formData.unit} onChange={e => setFormData({...formData, unit: e.target.value})}>
                    <option value="pcs">Pcs</option>
                    <option value="sheets">Sheets</option>
                    <option value="cft">Cubic Feet</option>
                    <option value="kg">Kg</option>
                    <option value="bottles">Bottles</option>
                    <option value="meters">Meters</option>
                  </select>
                </div>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-1">Price/Unit (LKR)</label>
                  <input required type="number" min="0" step="0.01" className="input-field" placeholder="e.g. 1500"
                    value={formData.price_per_unit} onChange={e => setFormData({...formData, price_per_unit: e.target.value})} />
                </div>
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-1">Purchase Date</label>
                  <input required type="date" className="input-field"
                    value={formData.purchased_date} onChange={e => setFormData({...formData, purchased_date: e.target.value})} />
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">Notes (Optional)</label>
                <input type="text" className="input-field" placeholder="e.g. Bought from ABC store"
                  value={formData.notes} onChange={e => setFormData({...formData, notes: e.target.value})} />
              </div>
              {formData.quantity && formData.price_per_unit && (
                <div className="bg-emerald-50 border border-emerald-200 rounded-lg p-3 text-sm text-emerald-800">
                  💰 Total: <strong>LKR {((parseFloat(formData.quantity)||0)*(parseFloat(formData.price_per_unit)||0)).toLocaleString()}</strong>
                </div>
              )}
              <div className="flex justify-end gap-3 pt-4 border-t border-slate-100">
                <button type="button" onClick={() => setIsModalOpen(false)} className="btn-secondary">Cancel</button>
                <button type="submit" disabled={saving} className="btn-primary">
                  {saving ? 'Saving...' : 'Save Purchase'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
